name: rice-classification

channels:
  - conda-forge

dependencies:
  - python=3.12

  - pip

  - pip:
      - mlflow==2.19.0
      - tensorflow==2.18.0
      - numpy
      - pandas
      - scikit-learn
      - pillow