name: MLflow Training

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0
          pip install tensorflow==2.18.0
          pip install numpy pandas scikit-learn pillow

      - name: Run Training
        run: |
          python MLProject/modelling.py
