name: MLflow Training

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0

      - name: Run Training
        run: |
          python MLProject/modelling.py

      - name: Create Artifact
        run: |
          mkdir artifacts
          echo "Workflow CI berhasil" > artifacts/result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: training-artifact
          path: artifacts/
